Added add boundary modal, and upload shapefile flow
terraware/terraware-web pull request #2923
Opened 2024-07-30 19:53 UTC by tommylau523

2024-07-30 19:53 UTC, tommylau523 commented
* **#2923** <a href="https://app.graphite.dev/github/pr/terraware/terraware-web/2923?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @tommylau523 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-30 21:56 UTC, nickgraz commented on src/scenes/ApplicationRouter/portal/Map/UpdateOrUploadBoundaryModal.tsx
> +        '&:active': { backgroundColor: rgb(isSelected ? 100 : 20) },
🔥

2024-07-30 21:58 UTC, nickgraz commented on src/scenes/ApplicationRouter/portal/MapUpdate/index.tsx
> +    if (boundaryAreaHa > 20000) {
```suggestion
    if (boundaryAreaHa > maxAreaHa) {
```

2024-07-30 22:01 UTC, nickgraz commented on src/scenes/ApplicationRouter/portal/MapUpdate/index.tsx
> +    const maxAreaHa = 20000;
Can you make this a top level const similar to `SQ_M_TO_HECTARES`? It can be towards the top of this file or the same file as that other const.

2024-07-30 22:03 UTC, nickgraz commented on src/scenes/ApplicationRouter/portal/MapUpdate/index.tsx
> +            <p>Watch a tutorial about drawing site boundaries.</p>
I think these should be localized

2024-07-30 22:05 UTC, nickgraz commented on src/scenes/ApplicationRouter/portal/MapUpdate/index.tsx
> +const MapView = () => {
Can you rename `MapView` to `MapUpdateView` and `MapViewWrapper` to `MapUpdateViewWrapper`?

2024-07-30 22:07 UTC, nickgraz commented on src/scenes/ApplicationRouter/portal/MapUpload/index.tsx
> +  const [isLoading, setIsLoading] = useState<boolean>(false);
Instead of creating more state, you can do something like `const isLoading = result?.status === 'pending'`

2024-07-30 22:08 UTC, nickgraz requested changes
This is looking great! Just a few minor things to look at

2024-07-31 16:31 UTC, nickgraz approved these changes
Looks good to me, thanks for the changes!

2024-07-31 17:37 UTC, merged